import MainLayout from "@/components/templates/layouts/main-layout";
import { montserrat } from "@/constants/fonts";
import "@/styles/globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Flow",
	description: "Generated by sina parsa :)))",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={montserrat.variable}>
			<body className={montserrat.className}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
